frontend/models/Bot.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "{{%bot}}".
 *
 * @property int $id
 * @property string $title
 * @property string $content
 * @property string $meta_title
 * @property string $meta_keywords
 * @property string $meta_description
 * @property string $username
 * @property string $token
 * @property string $start_param
 * @property string $image
 * @property int $views
 * @property int $status
 * @property int $published
 * @property int $default_category_id
 * @property int $author_by
 * @property int $added_by
 * @property int $moderated_by
 * @property int $created_at
 * @property int $updated_at
 *
 * @property BotCategory $defaultCategory
 * @property User $addedBy
 * @property User $authorBy
 * @property User $moderatedBy
 * @property BotComment[] $botComments
 * @property BotRating[] $botRatings
 */
class Bot extends \yii\db\ActiveRecord
{
    const STATUS_REJECTED = 0;
    const STATUS_APPROVED = 1;
    const STATUS_PANDING_APPROVED = 2;
    const STATUS_BANNED = 3;

    const UNPUBLISHED = 0;
    const PUBLISHED = 1;

    const START_PARAM = 'http://botshop.loc';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%bot}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'content', 'meta_title', 'username', 'image'], 'required'],
            [['content', 'meta_keywords', 'meta_description'], 'string'],
            [['views', 'status', 'published', 'default_category_id', 'author_by', 'added_by', 'moderated_by', 'created_at', 'updated_at'], 'integer'],
            [['title', 'meta_title', 'username', 'token', 'start_param', 'image'], 'string', 'max' => 255],
            [['username'], 'unique'],
            [['token'], 'unique'],
            ['start_param', 'default', 'value' => self::START_PARAM],
            ['status', 'default', 'value' => self::STATUS_PANDING_APPROVED],
            ['status', 'in', 'range' => [self::STATUS_PANDING_APPROVED, self::STATUS_REJECTED, self::STATUS_APPROVED, self::STATUS_BANNED]],
            ['published', 'default', 'value' => self::PUBLISHED],
            ['published', 'in', 'range' => [self::PUBLISHED, self::UNPUBLISHED]],
            [['default_category_id'], 'exist', 'skipOnError' => true, 'targetClass' => BotCategory::className(), 'targetAttribute' => ['default_category_id' => 'id']],
            [['added_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['added_by' => 'id']],
            [['author_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['author_by' => 'id']],
            [['moderated_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['moderated_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => \yii\behaviors\TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('frontend', 'ID'),
            'title' => Yii::t('frontend', 'Title'),
            'content' => Yii::t('frontend', 'Content'),
            'meta_title' => Yii::t('frontend', 'Meta Title'),
            'meta_keywords' => Yii::t('frontend', 'Meta Keywords'),
            'meta_description' => Yii::t('frontend', 'Meta Description'),
            'username' => Yii::t('frontend', 'Username'),
            'token' => Yii::t('frontend', 'Token'),
            'start_param' => Yii::t('frontend', 'Start Param'),
            'image' => Yii::t('frontend', 'Image'),
            'views' => Yii::t('frontend', 'Views'),
            'status' => Yii::t('frontend', 'Status'),
            'published' => Yii::t('frontend', 'Published'),
            'default_category_id' => Yii::t('frontend', 'Default Category ID'),
            'author_by' => Yii::t('frontend', 'Author By'),
            'added_by' => Yii::t('frontend', 'Added By'),
            'moderated_by' => Yii::t('frontend', 'Moderated By'),
            'created_at' => Yii::t('frontend', 'Created At'),
            'updated_at' => Yii::t('frontend', 'Updated At'),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function getBotById($id)
    {
        $query = self::find()->with(['botComments', 'botLanguages', 'botRatings'])->where(['username' => $id, 'status' => self::STATUS_APPROVED, 'published' => self::PUBLISHED]);

        return $query->one();
    }

    /**
     * {@inheritdoc}
     */
    public static function getListAll()
    {
        $query = self::find()->with(['botRatings'])->where(['status' => self::STATUS_APPROVED, 'published' => self::PUBLISHED]);

        return $query->all();
    }

    /**
     * {@inheritdoc}
     */
    public static function getBotBySearchText($q)
    {
        return self::find()
                    ->with(['botRatings'])
                    ->where(['status' => self::STATUS_APPROVED, 'published' => self::PUBLISHED])
                    ->andWhere(['or', ['like', 'meta_title', $q], ['like', 'title', $q], ['like', 'content', $q]])
                    ->all();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBotCategories()
    {
        return $this->hasMany(BotCategory::className(), ['id' => 'category_id'])->viaTable('bot_to_bot_category', ['bot_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBotLanguages()
    {
        return $this->hasMany(BotLanguage::className(), ['id' => 'bot_language_id'])->viaTable('bot_to_bot_language', ['bot_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBotTags()
    {
        return $this->hasMany(BotTag::className(), ['id' => 'tag_id'])->viaTable('bot_to_bot_tag', ['bot_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDefCategory()
    {
        return $this->hasOne(BotCategory::className(), ['id' => 'default_category_id'])->inverseOf('botsByDefCategory');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAddedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'added_by'])->inverseOf('bots');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthorBy()
    {
        return $this->hasOne(User::className(), ['id' => 'author_by'])->inverseOf('bots0');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getModeratedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'moderated_by'])->inverseOf('bots1');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBotComments()
    {
        return $this->hasMany(BotComment::className(), ['bot_id' => 'id'])->orderBy(['created_at' => SORT_DESC])->inverseOf('bot');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBotRatings()
    {
        return $this->hasMany(BotRating::className(), ['bot_id' => 'id'])->inverseOf('bot');
    }

    public function getStatusList()
    {
        return [
            Yii::t('frontend', 'Rejected'),
            Yii::t('frontend', 'Approved'),
            Yii::t('frontend', 'Panding approved'),
            Yii::t('frontend', 'Banned'),
        ];
    }

    public function getStatusName()
    {
        $statusList = $this->getStatusList();

        return $statusList[$this->status];
    }

    public function getPublishedList()
    {
        return [
            Yii::t('frontend', 'Unpublished'),
            Yii::t('frontend', 'Published'),
        ];
    }

    public function getPublishedName()
    {
        $publishedList = $this->getPublishedList();

        return $publishedList[$this->published];
    }
}

backend/controllers/BotController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Bot;
use backend\models\BotSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BotController implements the CRUD actions for Bot model.
 */
class BotController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Bot models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BotSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Bot model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Bot model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Bot();

        if ($model->load(Yii::$app->request->post()) && $model->save(false)) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Bot model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Bot model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Bot model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Bot the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Bot::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('backend', 'The requested page does not exist.'));
    }
}

frontend/controllers/BotController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\data\ActiveDataProvider;

use frontend\models\Bot;
use frontend\models\BotRating;
use frontend\models\BotCategory;
use frontend\models\BotComment;
use frontend\models\BotLanguage;
use frontend\models\Language;

use \frontend\models\forms\CommentForm;

class BotController extends Controller
{
    const BOTS_PER_PAGE = 40;

    public function behaviors() {
		return [
			'cache' => [
				'class' =>'yii\filters\PageCache',
    			'only' => ['index', 'category'],
				'duration' => 0,
				'dependency' => [
			       'class' => 'yii\caching\DbDependency',
			       'sql' => 'SELECT max(updated_at) AS max FROM bot',
				],
                'variations' => [
                    Yii::$app->language,
                ],
			]
		];
	}

    public function beforeAction($action)
    {
        $model = new \frontend\models\forms\SearchForm;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $q = \yii\helpers\Html::encode($model->q);

            return $this->redirect(['bot/search', 'q' => $q]);
        }

        return true;
    }

    public function actionIndex()
    {
    	$data = [];

        $data['language_id'] = Language::getLanguageIdByCode(Yii::$app->language);
        $data['categories'] = BotCategory::getList();
        $data['bots'] = Bot::findAll(['published' => Bot::PUBLISHED, 'status' => Bot::STATUS_APPROVED]);

        return $this->render('index', $data);
    }

    public function actionCategory($category)
    {
    	$data = [];

        $data['language_id'] = Language::getLanguageIdByCode(Yii::$app->language);

        $modelCategory = BotCategory::getCategoryById($category);

        if(!$modelCategory) {
            throw new BadRequestHttpException(Yii::t('frontend', 'This category does not exist!'));
        }

        $data['category'] = $modelCategory;
        $data['categories'] = BotCategory::getList();
        $data['bots'] = BotCategory::find()->where(['slug' => $category])->with('bots')->one()->bots;

    	return $this->render('category', $data);
    }

    public function actionView($category, $bot)
    {
    	$data = [];

        $request = Yii::$app->request;
        $session = Yii::$app->session;

        $modelCategory = BotCategory::getCategoryById($category);
        $modelBot = Bot::getBotById($bot);

        if(!$modelCategory) {
            throw new BadRequestHttpException(Yii::t('frontend', 'This category does not exist!'));
        }

        if(!$modelBot) {
            throw new BadRequestHttpException(Yii::t('frontend', 'This bot does not exist!'));
        }

        if (!$session->isActive) $session->open();

        if($session->hasFlash('comment_success')) {
            $data['comment_success'] = $session->getFlash('comment_error');
        }

        if($session->hasFlash('comment_error')) {
            $data['comment_error'] = $session->getFlash('comment_error');
        }

        $commentForm = new CommentForm;

        $commentForm->bot_id = $bot->id;

        if($request->isPost) {
            if(!Yii::$app->user->isGuest) {
                if($commentForm->load($request->post())) {
                    if($commentForm->addComment()) {
                        $session->setFlash('comment_success', Yii::t('frontend', 'Comment successfully added!'));

                        return $this->redirect(['bot/view', 'category' => $category, 'bot' => $bot, '#' => 'comments']);
                    } else {
                        $session->setFlash('comment_error', Yii::t('frontend', 'Unprocessed error!'));
                    }
                }
            } else {
                $session->setFlash('comment_error', Yii::t('frontend', 'You must be logged in!'));
            }
        }

        $data['category'] = $modelCategory;
        $data['bot'] = $modelBot;
        $data['commentForm'] = $commentForm;

    	return $this->render('view', $data);
    }

    public function actionSearch($q)
    {
        $data = [];

        //$q = Yii::$app->request->get('q');

        $data['search'] = $q;
        $data['language_id'] = Language::getLanguageIdByCode(Yii::$app->language);
        $data['categories'] = BotCategory::getList();
        $data['bots'] = Bot::getBotBySearchText($q);

        return $this->render('search', $data);
    }

    /*public function actionComment()
    {
        $request = Yii::$app->request;

        $commentForm = new CommentForm;

        if($requst->isPost) {
            if($commentForm->load($request->post())) {
                $comment = $commentForm->addComment();

                if($comment) {
                    $session->setFlash('comment_success', Yii::t('frontend', 'Comment successfully added!'));
                } else {
                    $session->setFlash('comment_error', Yii::t('frontend', 'Error send comment'));
                }

                return $this->redirect(['bot/view', 'category' => $comment->bot->defCategory->slug, 'bot' => $comment->bot->username]);
            }
        }

        return $this->redirect(['bot/index']);
    }*/
}

frontend/views/bot/_bot.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Menu;
use rmrevin\yii\fontawesome\FA;
use kartik\rating\StarRating;

?>
<div class="col-md-6">
    <div class="panel panel-default item-bot">
        <div class="panel-heading">
            <h2 class="panel-title"><?= $bot->title ?></h2>
        </div>
        <div class="panel-body">
            <p class="clearfix text-left">
                <?= Html::img('@web/uploads/bots/' . $bot->image, ['class' => 'pull-left', 'style' => 'max-width:120px;width:100%;border-radius:50%;margin-right:15px;']) ?>
                <?= $bot->content ?>
                <?= StarRating::widget([
                    'name' => 'rating_' . $bot->id,
                    'value' => 3,
                    'language' => Yii::$app->language,
                    'pluginOptions' => [
                        'theme' => 'krajee-svg',
                        'filledStar' => '<span class="krajee-icon krajee-icon-star"></span>',
                        'emptyStar' => '<span class="krajee-icon krajee-icon-star"></span>',
                        //'disabled' => true,
                        'showClear' => false,
                        'showCaption' => false,
                        'step' => 1,
                    ],
                ]); ?>
            </p>
        </div>
        <div class="panel-footer clearfix">
            <?= Html::a(Fa::icon('eye'), Url::to(['bot/view', 'category' => isset($category) ? $category->slug : $bot->defCategory->slug, 'bot' => $bot->username]), ['class' => 'btn btn-primary btn-flat pull-left', 'data-toggle' => 'tooltip', 'title' => Yii::t('yii', 'View')]) ?>
            <?= Html::a(Yii::t('frontend', 'Add to {icon}', ['icon' => FA::icon('paper-plane-o')]), 'https://t.me/' . $bot->username . ($bot->start_param ? '?start=' . $bot->start_param : ''), ['class' => 'btn btn-success btn-flat pull-right', 'target' => '_blank']) ?>
        </div>
    </div>
</div>

frontend/views/bot/_categories.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use valiant\widgets\ListGroupWidget;

$request = Yii::$app->request;

$menuItems = [];

if($categories) {
    foreach($categories as $category) {
        $menuItems[] = [
            'label' => $category->title . ' (' . $category->getBots()->count() . ') ',
            'url' => Url::to(['bot/category', 'category' => $category->slug]),
            'options' => ['class' => 'list-group-item'],
            'active' => isset($request->get['category']) && $request->get['category'] == $category->slug,
        ];
    }

    echo ListGroupWidget::widget([
        'items' => $menuItems,
        'options' => ['class' => 'list-group'],
        //'active' => true,
    ]);
} else { ?>
<div class="alert alert-warning">
    <p><?= Yii::t('frontend', 'The list of categories is not filled!') ?></p>
</div>
<?php } ?>

frontend/views/bot/_comment.php
<?php

use yii\helpers\Html;

?>
<div class="page-comment">
    <?= Html::a('@' . $comment->author, 'http://t.me/' . $comment->author, ['class' => 'comment-username', 'target' => '_blank']) ?>

    <span class="com-date pull-right"><?= $comment->created_at ?></span>

    <p><?= $comment->content ?></p>
</div>

frontend/views/bot/_comment_form.php
<?php

use yii\helpers\Html;
use rmrevin\yii\fontawesome\FA;
use yii\bootstrap\ActiveForm;
// use yii\widgets\Pjax;

?>
<?php if(!empty($comment_success)) { ?>
<div class="alert alert-success alert-dismissible"><i class="fa fa-check-circle"></i> <?= $comment_success ?>
    <button type="button" class="close" data-dismiss="alert">×</button>
</div>
<?php } ?>

<?php if(!empty($comment_error)) { ?>
<div class="alert alert-danger alert-dismissible"><i class="fa fa-times-circle"></i> <?= $comment_error ?>
    <button type="button" class="close" data-dismiss="alert">×</button>
</div>
<?php } ?>

<?php $form = ActiveForm::begin(); ?>

<?= $form->field($commentForm, 'bot_id')->hiddenInput(['value' => $bot_id])->label(false); ?>

<?= $form->field($commentForm, 'comment')->textarea(['rows' => 3]) ?>

<div class="form-group clearfix">
    <?= Html::submitButton(Yii::t('frontend', '{icon} Send', ['icon' => FA::icon('paper-plane-o')]), ['class' => 'btn btn-primary btn-flat pull-right']) ?>
</div>

<?php ActiveForm::end(); ?>

frontend/views/bot/category.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = Yii::t('frontend', 'Catalog') . ' - ' . $category->meta_title;

$this->params['breadcrumbs'][] = [
    'label' => Yii::t('frontend', 'Bots Catalog'),
    'url' => Url::to(['bot/index']),
];
$this->params['breadcrumbs'][] = $category->title;

$this->registerMetaTag([
  'name' => 'description',
  'content' => $category->meta_description,
]);

$this->registerMetaTag([
  'name' => 'keywords',
  'content' => $category->meta_keywords,
]);
?>
<div class="catalog-index">
    <div class="page-header">
        <h1><?= Yii::t('frontend', 'Catalog') . ': ' . $category->title ?></h1>
    </div>

    <div class="row">
        <div class="col-md-3">
            <?= $this->render('_categories', ['categories' => $categories]) ?>
        </div>

        <div class="col-md-9">
            <?php if($bots) { ?>
            <?php foreach($bots as $bot) { ?>
            <?= $this->render('_bot', ['bot' => $bot, 'category' => $category]) ?>
            <?php } ?>
            <?php } else { ?>
            <div class="alert alert-danger">
                <p><?= Yii::t('frontend', 'There is nothing in this category!') ?></p>
            </div>
            <?php } ?>
        </div>
    </div>
</div>

frontend/views/bot/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = Yii::t('frontend', 'Bots Catalog') . '';

$this->params['breadcrumbs'][] = $this->title;

$this->registerMetaTag([
  'name' => 'description',
  'content' => 'Meta description',
]);

$this->registerMetaTag([
  'name' => 'keywords',
  'content' => 'meta, tags, for, your, site',
]);
?>
<div class="catalog-index">
    <div class="page-header">
        <h1><?= $this->title ?></h1>
    </div>

    <div class="row">
        <div class="col-md-3">
            <?= $this->render('_categories', ['categories' => $categories]) ?>
        </div>

        <div class="col-md-9">
            <?php if($bots) { ?>
            <?php foreach($bots as $bot) { ?>
            <?= $this->render('_bot', ['bot' => $bot]) ?>
            <?php } ?>
            <?php } else { ?>
            <div class="alert alert-danger">
                <p><?= Yii::t('frontend', 'There is nothing in the catalog!') ?></p>
            </div>
            <?php } ?>
        </div>
    </div>
</div>

frontend/views/bot/search.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = Yii::t('frontend', 'Bots Catalog') . ' - Поиск ботов';

$this->params['breadcrumbs'][] = [
    'label' => Yii::t('frontend', 'Bots Catalog'),
    'url' => Url::to(['bot/index']),
];
$this->params['breadcrumbs'][] = $search;
?>
<div class="catalog-search">
    <div class="page-header">
        <h1><?= Yii::t('frontend', 'Response to query: {query}', ['query' => $search, /*'<i><b>' . $search . '</b></i>'*/]) ?></h1>
    </div>

    <div class="row">
        <div class="col-md-3">
            <?= $this->render('_categories', ['categories' => $categories]) ?>
        </div>

        <div class="col-md-9">
            <?php if($bots) { ?>
            <?php foreach($bots as $bot) { ?>
            <?= $this->render('_bot', ['bot' => $bot]) ?>
            <?php } ?>
            <?php } else { ?>
            <div class="alert alert-danger">
                <p><?= Yii::t('frontend', 'At your request, nothing found!') ?></p>
            </div>
            <?php } ?>
        </div>
    </div>
</div>

frontend/views/bot/view.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use kartik\rating\StarRating;
use rmrevin\yii\fontawesome\FA;
use yii\bootstrap\ActiveForm;
use yii\widgets\Pjax;

$js = <<<JS

jQuery('#comment-form').submit(function () {
    // send data to actionSave by ajax request.
    return false; // Cancel form submitting.
});

JS;

//$this->registerJs($js);

$this->title = Yii::t('frontend', 'Catalog') . ' - ' . $bot->meta_title;

$this->params['breadcrumbs'][] = [
    'label' => Yii::t('frontend', 'Bots Catalog'),
    'url' => Url::to(['bot/index']),
];
$this->params['breadcrumbs'][] = [
    'label' => $category->title,
    'url' => ['bot/category', 'category' => $category->slug],
];
$this->params['breadcrumbs'][] = $bot->title;

$this->registerMetaTag([
  'name' => 'description',
  'content' => $bot->meta_description,
]);

$this->registerMetaTag([
  'name' => 'keywords',
  'content' => $bot->meta_keywords,
]);
?>
<div class="catalog-view">
    <div class="page-header">
        <h1><?= $bot->title ?></h1>
    </div>

    <div class="row">
        <div class="col-md-3">
            <div class="bot-avatar">
                <p class="text-center"><?= Html::img('@web/uploads/bots/' . $bot->image, ['style' => 'border-radius:50%;max-width:150px;width:100%;']) ?></p>
                <p class="text-center"><?= StarRating::widget([
                    'name' => 'rating_' . $bot->id,
                    'value' => 3,
                    'language' => Yii::$app->language,
                    'pluginOptions' => [
                        //'disabled' => true,
                        'showClear' => false,
                        'showCaption' => false,
                        'step' => 1,
                    ],
                ]); ?></p>
                <p class="text-center"><?= Html::a(Yii::t('frontend', 'Add to {icon}', ['icon' => Fa::icon('telegram')]), 'https://t.me/' . $bot->username . ($bot->start_param ? '?start=' . $bot->start_param : ''), ['class' => 'btn btn-primary btn-flat', 'style' => 'font-size: 18px;', 'target' => '_blank']) ?></p>
            </div>
            <div class="bot-languages">
                <h4><?= Yii::t('frontend', 'Supported language') ?>:</h4>
                <?php foreach($bot->botLanguages as $language) { ?>
                <p class="label label-success"><?= $language->name ?></p>
                <?php } ?>
            </div>
        </div>

        <div class="col-md-9">
            <h3><?= Yii::t('frontend', 'Description') ?>:</h3>
            <?= $bot->content ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3"></div>

        <div class="col-md-9">
            <!-- Nav tabs -->
            <div class="bot-comment">
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active">
                        <a href="#comments" aria-controls="comments" role="tab" data-toggle="tab"><?= Yii::t('frontend', 'Comments') ?></a>
                    </li>
                    <li role="presentation">
                        <a href="#reports" aria-controls="reports" role="tab" data-toggle="tab"><?= Yii::t('frontend', 'Reports') ?></a>
                    </li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane fade in active" id="comments">
                        <div class="comment-editor">
                            <?= $this->render('_comment_form', [
                                'commentForm' => $commentForm,
                                'bot_id' => $bot->id,
                                'comment_success' => isset($comment_success) ? $comment_success : null,
                                'comment_error' => isset($comment_error) ? $comment_error : null,
                            ]) ?>
                        </div>

                        <?php foreach($bot->botComments as $comment) { ?>
                        <?= $this->render('_comment', ['comment' => $comment]) ?>
                        <?php } ?>
                    </div>
                    <div role="tabpanel" class="tab-pane fade" id="reports">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>