frontend/models/Bot.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "{{%bot}}".
 *
 * @property int $id
 * @property string $title
 * @property string $content
 * @property string $meta_title
 * @property string $meta_keywords
 * @property string $meta_description
 * @property string $username
 * @property string $token
 * @property string $start_param
 * @property string $image
 * @property int $views
 * @property int $status
 * @property int $published
 * @property int $default_category_id
 * @property int $author_by
 * @property int $added_by
 * @property int $moderated_by
 * @property int $created_at
 * @property int $updated_at
 *
 * @property BotCategory $defaultCategory
 * @property User $addedBy
 * @property User $authorBy
 * @property User $moderatedBy
 * @property BotComment[] $botComments
 * @property BotRating[] $botRatings
 */
class Bot extends \yii\db\ActiveRecord
{
    const STATUS_REJECTED = 0;
    const STATUS_APPROVED = 1;
    const STATUS_PANDING_APPROVED = 2;
    const STATUS_BANNED = 3;

    const UNPUBLISHED = 0;
    const PUBLISHED = 1;

    const START_PARAM = 'http://botshop.loc';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%bot}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'content', 'meta_title', 'username', 'image'], 'required'],
            [['content', 'meta_keywords', 'meta_description'], 'string'],
            [['views', 'status', 'published', 'default_category_id', 'author_by', 'added_by', 'moderated_by', 'created_at', 'updated_at'], 'integer'],
            [['title', 'meta_title', 'username', 'token', 'start_param', 'image'], 'string', 'max' => 255],
            [['username'], 'unique'],
            [['token'], 'unique'],
            ['start_param', 'default', 'value' => self::START_PARAM],
            ['status', 'default', 'value' => self::STATUS_PANDING_APPROVED],
            ['status', 'in', 'range' => [self::STATUS_PANDING_APPROVED, self::STATUS_REJECTED, self::STATUS_APPROVED, self::STATUS_BANNED]],
            ['published', 'default', 'value' => self::PUBLISHED],
            ['published', 'in', 'range' => [self::PUBLISHED, self::UNPUBLISHED]],
            [['default_category_id'], 'exist', 'skipOnError' => true, 'targetClass' => BotCategory::className(), 'targetAttribute' => ['default_category_id' => 'id']],
            [['added_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['added_by' => 'id']],
            [['author_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['author_by' => 'id']],
            [['moderated_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['moderated_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => \yii\behaviors\TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('frontend', 'ID'),
            'title' => Yii::t('frontend', 'Title'),
            'content' => Yii::t('frontend', 'Content'),
            'meta_title' => Yii::t('frontend', 'Meta Title'),
            'meta_keywords' => Yii::t('frontend', 'Meta Keywords'),
            'meta_description' => Yii::t('frontend', 'Meta Description'),
            'username' => Yii::t('frontend', 'Username'),
            'token' => Yii::t('frontend', 'Token'),
            'start_param' => Yii::t('frontend', 'Start Param'),
            'image' => Yii::t('frontend', 'Image'),
            'views' => Yii::t('frontend', 'Views'),
            'status' => Yii::t('frontend', 'Status'),
            'published' => Yii::t('frontend', 'Published'),
            'default_category_id' => Yii::t('frontend', 'Default Category ID'),
            'author_by' => Yii::t('frontend', 'Author By'),
            'added_by' => Yii::t('frontend', 'Added By'),
            'moderated_by' => Yii::t('frontend', 'Moderated By'),
            'created_at' => Yii::t('frontend', 'Created At'),
            'updated_at' => Yii::t('frontend', 'Updated At'),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function getBotById($id)
    {
        $query = self::find()->with(['botComments', 'botLanguages', 'botRatings'])->where(['username' => $id, 'status' => self::STATUS_APPROVED, 'published' => self::PUBLISHED]);

        return $query->one();
    }

    /**
     * {@inheritdoc}
     */
    public static function getListAll()
    {
        $query = self::find()->with(['botRatings'])->where(['status' => self::STATUS_APPROVED, 'published' => self::PUBLISHED]);

        return $query->all();
    }

    /**
     * {@inheritdoc}
     */
    public static function getBotBySearchText($q)
    {
        return self::find()
                    ->with(['botRatings'])
                    ->where(['status' => self::STATUS_APPROVED, 'published' => self::PUBLISHED])
                    ->andWhere(['or', ['like', 'meta_title', $q], ['like', 'title', $q], ['like', 'content', $q]])
                    ->all();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBotCategories()
    {
        return $this->hasMany(BotCategory::className(), ['id' => 'category_id'])->viaTable('bot_to_bot_category', ['bot_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBotLanguages()
    {
        return $this->hasMany(BotLanguage::className(), ['id' => 'bot_language_id'])->viaTable('bot_to_bot_language', ['bot_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBotTags()
    {
        return $this->hasMany(BotTag::className(), ['id' => 'tag_id'])->viaTable('bot_to_bot_tag', ['bot_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDefCategory()
    {
        return $this->hasOne(BotCategory::className(), ['id' => 'default_category_id'])->inverseOf('botsByDefCategory');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAddedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'added_by'])->inverseOf('bots');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthorBy()
    {
        return $this->hasOne(User::className(), ['id' => 'author_by'])->inverseOf('bots0');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getModeratedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'moderated_by'])->inverseOf('bots1');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBotComments()
    {
        return $this->hasMany(BotComment::className(), ['bot_id' => 'id'])->orderBy(['created_at' => SORT_DESC])->inverseOf('bot');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBotRatings()
    {
        return $this->hasMany(BotRating::className(), ['bot_id' => 'id'])->inverseOf('bot');
    }

    public function getStatusList()
    {
        return [
            Yii::t('frontend', 'Rejected'),
            Yii::t('frontend', 'Approved'),
            Yii::t('frontend', 'Panding approved'),
            Yii::t('frontend', 'Banned'),
        ];
    }

    public function getStatusName()
    {
        $statusList = $this->getStatusList();

        return $statusList[$this->status];
    }

    public function getPublishedList()
    {
        return [
            Yii::t('frontend', 'Unpublished'),
            Yii::t('frontend', 'Published'),
        ];
    }

    public function getPublishedName()
    {
        $publishedList = $this->getPublishedList();

        return $publishedList[$this->published];
    }
}

frontend/models/Post.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "{{%post}}".
 *
 * @property int $id
 * @property string $image
 * @property string $slug
 * @property int $status
 * @property int $created_by
 * @property int $updated_by
 * @property int $created_at
 * @property int $updated_at
 *
 * @property User $createdBy
 * @property User $updatedBy
 * @property PostComment[] $postComments
 * @property PostTrasnlate[] $postTrasnlates
 */
class Post extends \yii\db\ActiveRecord
{
    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 1;

    public $title;
    public $preview_content;
    public $content;
    public $meta_title;
    public $meta_keywords;
    public $meta_description;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%post}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['slug', 'created_at', 'updated_at'], 'required'],
            [['status', 'created_by', 'updated_by', 'created_at', 'updated_at'], 'integer'],
            [['image', 'slug'], 'string', 'max' => 255],
            [['slug'], 'unique'],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_INACTIVE]],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['updated_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('frontend', 'ID'),
            'image' => Yii::t('frontend', 'Image'),
            'slug' => Yii::t('frontend', 'Slug'),
            'status' => Yii::t('frontend', 'Status'),
            'created_by' => Yii::t('frontend', 'Created By'),
            'updated_by' => Yii::t('frontend', 'Updated By'),
            'created_at' => Yii::t('frontend', 'Created At'),
            'updated_at' => Yii::t('frontend', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by'])->inverseOf('posts');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by'])->inverseOf('posts0');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPostComments()
    {
        return $this->hasMany(PostComment::className(), ['post_id' => 'id'])->inverseOf('post');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPostTranslates()
    {
        return $this->hasMany(PostTranslate::className(), ['post_id' => 'id'])->inverseOf('post');
    }
}

frontend/controllers/PostController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;

use frontend\models\Post;
use frontend\models\PostCategory;

class PostController extends Controller
{
    public function actionIndex()
    {
        $data = [];

        // $data['categories'] = PostCategory::find()->where(['status' => PostCategory::STATUS_ACTIVE])->all();

        return $this->render('index', $data);
    }

    public function actionCategory($category)
    {
        $data = [];

        return $this->render('category', $data);
    }

    public function actionView($category, $post)
    {
        $data = [];

        return $this->render('view', $data);
    }
}

frontend/views/post/_categories.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
// use yii\widgets\Menu;
use valiant\widgets\ListGroupWidget as Menu;

$menuItems = [];

if($categories) {
    foreach($categories as $category) {
        $menuItems[] = [
            'label' => $category->title . ' (' . $category->getBots()->count() . ') ',
            'url' => Url::to(['blog/category', 'category' => $category->slug]),
            'options' => ['class' => 'list-group-item'],
            'active' => Yii::$app->request->get('category') == $category->slug,
        ];
    }

    echo Menu::widget([
        'items' => $menuItems,
        'options' => ['class' => 'list-group'],
    ]);
} else { ?>
<div class="alert alert-warning">
    <p><?= Yii::t('frontend', 'The list of categories is not filled!') ?></p>
</div>
<?php } ?>

frontend/views/post/_post.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Menu;
use rmrevin\yii\fontawesome\FA;

?>
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title"><?= $post->title ?></h2>
        </div>
        <div class="panel-body">
            <p><?= $post->preview_content ?></p>
        </div>
        <div class="panel-footer clearfix">
            <?= Html::a(Fa::icon('eye'), Url::to(['post/view', 'category' => isset($category) ? $category->slug : $post->defCategory->slug, 'post' => $post->slug]), ['class' => 'btn btn-primary btn-flat pull-right']) ?>
        </div>
    </div>
</div>

frontend/views/post/category.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = Yii::t('frontend', 'Posts') . ' - ' . $category->title;

$this->params['breadcrumbs'][] = [
    'label' => Yii::t('frontend', 'Posts'),
    'url' => ['blog/index'],
];
$this->params['breadcrumbs'][] = $category->title;
?>
<div class="post-category">
    <div class="page-header">
        <h1><?= $category->title ?></h1>
    </div>

    <div class="row">
        <div class="col-md-3">
            <?= $this->render('_categories', ['categories' => $categories]) ?>
        </div>

        <div class="col-md-9">
            <?php if($posts) { ?>
            <?php foreach($posts as $post) { ?>
            <?= $this->render('_post', ['post' => $post, 'category' => $category]) ?>
            <?php } ?>
            <?php } else { ?>
            <div class="alert alert-danger">
                <p><?= Yii::t('frontend', 'There is nothing in the blog!') ?></p>
            </div>
            <?php } ?>
        </div>
    </div>
</div>

frontend/views/post/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = Yii::t('frontend', 'Posts');

$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-index">
    <div class="page-header">
        <h1><?= $this->title ?></h1>
    </div>

    <div class="row">
        <div class="col-md-3">
            <?= $this->render('_categories', ['categories' => $categories]) ?>
        </div>

        <div class="col-md-9">
            <?php if($posts) { ?>
            <?php foreach($posts as $post) { ?>
            <?= $this->render('_post', ['post' => $post]) ?>
            <?php } ?>
            <?php } else { ?>
            <div class="alert alert-danger">
                <p><?= Yii::t('frontend', 'There is nothing in the blog!') ?></p>
            </div>
            <?php } ?>
        </div>
    </div>
</div>